# syntax=docker/dockerfile:1.7

FROM golang:1.26.2-alpine AS air-builder

ARG AIR_VERSION=v1.63.0

RUN --mount=type=cache,target=/go/pkg/mod --mount=type=cache,target=/root/.cache/go-build \
    go install github.com/air-verse/air@${AIR_VERSION}

FROM golang:1.26.2-alpine

ENV CGO_ENABLED=0 \
    GOFLAGS="-mod=mod -buildvcs=false" \
    GOPATH=/go \
    GOMODCACHE=/go/pkg/mod \
    PATH=/usr/local/go/bin:/go/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin

RUN apk add --no-cache ca-certificates curl git make openssh-client \
    && mkdir -p /go/pkg/mod /root/.cache/go-build \
    && go version

COPY --link --from=air-builder /go/bin/air /usr/local/bin/air

WORKDIR /workspace

COPY --link go.mod go.sum* ./
RUN go mod download

COPY --link . .
RUN go build -buildvcs=false -o /usr/local/bin/go-fibe ./cmd/go-fibe

CMD ["go-fibe", "serve"]
