package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/fibegg/go-fibe/graph/generated"
	"github.com/fibegg/go-fibe/graph/model"
	"github.com/fibegg/go-fibe/internal/ability"
	"github.com/fibegg/go-fibe/internal/cache"
	"github.com/fibegg/go-fibe/internal/db"
	"github.com/fibegg/go-fibe/internal/jobs"
	"github.com/fibegg/go-fibe/internal/maintenance"
	"github.com/fibegg/go-fibe/internal/models"
)

// CreateMonitor is the resolver for the createMonitor field.
func (r *mutationResolver) CreateMonitor(ctx context.Context, input model.MonitorInput) (*models.Monitor, error) {
	if _, err := ability.Require(ctx, ability.ActionManage, ability.ResourceMonitor); err != nil {
		return nil, err
	}
	validated, err := validateMonitorInput(r.Runtime.Config, input)
	if err != nil {
		return nil, err
	}
	monitor, err := r.Runtime.Store.CreateMonitor(ctx, validated)
	if err != nil {
		return nil, internalError(err)
	}
	_ = cache.Delete(ctx, r.Runtime.Redis, "cache:dashboard", "cache:public_status")
	jobs.PublishEvent(ctx, r.Runtime, "monitor:"+monitor.ID+":created")
	return &monitor, nil
}

// DeleteMonitor is the resolver for the deleteMonitor field.
func (r *mutationResolver) DeleteMonitor(ctx context.Context, id string) (bool, error) {
	if _, err := ability.Require(ctx, ability.ActionManage, ability.ResourceMonitor); err != nil {
		return false, err
	}
	deleted, err := r.Runtime.Store.DeleteMonitor(ctx, id)
	if err != nil {
		return false, internalError(err)
	}
	_ = cache.Delete(ctx, r.Runtime.Redis, "cache:dashboard", "cache:public_status")
	if deleted {
		jobs.PublishEvent(ctx, r.Runtime, "monitor:"+id+":deleted")
	}
	return deleted, nil
}

// EnqueueCheck is the resolver for the enqueueCheck field.
func (r *mutationResolver) EnqueueCheck(ctx context.Context, monitorID string) (string, error) {
	if _, err := ability.Require(ctx, ability.ActionRun, ability.ResourceJob); err != nil {
		return "", err
	}
	exists, err := r.Runtime.Store.MonitorExists(ctx, monitorID)
	if err != nil {
		return "", internalError(err)
	}
	if !exists {
		return "", fmt.Errorf("not found")
	}
	id, err := jobs.Enqueue(ctx, r.Runtime, jobs.Job{Type: jobs.TypeCheckMonitor, MonitorID: monitorID})
	if err != nil {
		return "", internalError(err)
	}
	return id, nil
}

// OpenIncident is the resolver for the openIncident field.
func (r *mutationResolver) OpenIncident(ctx context.Context, input model.IncidentInput) (*models.Incident, error) {
	if _, err := ability.Require(ctx, ability.ActionManage, ability.ResourceIncident); err != nil {
		return nil, err
	}
	title := cleanRequired(input.Title, 160)
	if title == "" {
		return nil, fmt.Errorf("title is required")
	}
	severity := strings.ToLower(valueOr(input.Severity, "minor"))
	if severity != "minor" && severity != "major" && severity != "critical" {
		return nil, fmt.Errorf("severity is invalid")
	}
	if input.MonitorID != nil {
		exists, err := r.Runtime.Store.MonitorExists(ctx, *input.MonitorID)
		if err != nil {
			return nil, internalError(err)
		}
		if !exists {
			return nil, fmt.Errorf("not found")
		}
	}
	incident, err := r.Runtime.Store.OpenIncident(ctx, models.IncidentInput{
		MonitorID: input.MonitorID,
		Title:     title,
		Severity:  severity,
	})
	if err != nil {
		return nil, internalError(err)
	}
	_ = cache.Delete(ctx, r.Runtime.Redis, "cache:dashboard", "cache:public_status")
	jobs.PublishEvent(ctx, r.Runtime, "incident:"+incident.ID+":open")
	return &incident, nil
}

// ResolveIncident is the resolver for the resolveIncident field.
func (r *mutationResolver) ResolveIncident(ctx context.Context, id string) (*models.Incident, error) {
	if _, err := ability.Require(ctx, ability.ActionManage, ability.ResourceIncident); err != nil {
		return nil, err
	}
	incident, err := r.Runtime.Store.ResolveIncident(ctx, id)
	if err != nil {
		if db.IsNoRows(err) {
			return nil, fmt.Errorf("not found")
		}
		return nil, internalError(err)
	}
	_ = cache.Delete(ctx, r.Runtime.Redis, "cache:dashboard", "cache:public_status")
	jobs.PublishEvent(ctx, r.Runtime, "incident:"+incident.ID+":resolved")
	return &incident, nil
}

// RunMaintenanceTask is the resolver for the runMaintenanceTask field.
func (r *mutationResolver) RunMaintenanceTask(ctx context.Context, name string) (*models.MaintenanceRun, error) {
	if _, err := ability.Require(ctx, ability.ActionRun, ability.ResourceMaintenance); err != nil {
		return nil, err
	}
	taskName := strings.TrimSpace(name)
	if !maintenance.Exists(taskName) {
		return nil, fmt.Errorf("maintenance task not found")
	}
	run, err := r.Runtime.Store.InsertMaintenanceRun(ctx, taskName)
	if err != nil {
		return nil, internalError(err)
	}
	jobType := maintenanceJobType(taskName)
	jobID, err := jobs.Enqueue(ctx, r.Runtime, jobs.Job{Type: jobType})
	status := "succeeded"
	output := "queued background job " + jobID
	if err != nil {
		status = "failed"
		output = "failed to queue background job"
	}
	completed, err := r.Runtime.Store.CompleteMaintenanceRun(ctx, run.ID, status, &output)
	if err != nil {
		return nil, internalError(err)
	}
	return &completed, nil
}

// Viewer is the resolver for the viewer field.
func (r *queryResolver) Viewer(ctx context.Context) (*models.CurrentUser, error) {
	user, ok := ability.UserFromContext(ctx)
	if !ok {
		return nil, nil
	}
	return &user, nil
}

// Dashboard is the resolver for the dashboard field.
func (r *queryResolver) Dashboard(ctx context.Context) (*models.Dashboard, error) {
	if _, err := ability.Require(ctx, ability.ActionRead, ability.ResourceMonitor); err != nil {
		return nil, err
	}
	if cached, ok, err := cache.GetJSON[models.Dashboard](ctx, r.Runtime.Redis, "cache:dashboard"); err == nil && ok {
		return &cached, nil
	}
	dashboard, err := r.Runtime.Store.Dashboard(ctx)
	if err != nil {
		return nil, internalError(err)
	}
	_ = cache.SetJSON(ctx, r.Runtime.Redis, "cache:dashboard", dashboard, 10*time.Second)
	return &dashboard, nil
}

// Monitors is the resolver for the monitors field.
func (r *queryResolver) Monitors(ctx context.Context) ([]*models.Monitor, error) {
	if _, err := ability.Require(ctx, ability.ActionRead, ability.ResourceMonitor); err != nil {
		return nil, err
	}
	monitors, err := r.Runtime.Store.ListMonitors(ctx)
	if err != nil {
		return nil, internalError(err)
	}
	return monitorPointers(monitors), nil
}

// CheckEvents is the resolver for the checkEvents field.
func (r *queryResolver) CheckEvents(ctx context.Context, monitorID string) ([]*models.CheckEvent, error) {
	if _, err := ability.Require(ctx, ability.ActionRead, ability.ResourceMonitor); err != nil {
		return nil, err
	}
	exists, err := r.Runtime.Store.MonitorExists(ctx, monitorID)
	if err != nil {
		return nil, internalError(err)
	}
	if !exists {
		return nil, fmt.Errorf("not found")
	}
	events, err := r.Runtime.Store.CheckEvents(ctx, monitorID)
	if err != nil {
		return nil, internalError(err)
	}
	return checkEventPointers(events), nil
}

// Incidents is the resolver for the incidents field.
func (r *queryResolver) Incidents(ctx context.Context) ([]*models.Incident, error) {
	if _, err := ability.Require(ctx, ability.ActionRead, ability.ResourceIncident); err != nil {
		return nil, err
	}
	incidents, err := r.Runtime.Store.ListIncidents(ctx)
	if err != nil {
		return nil, internalError(err)
	}
	return incidentPointers(incidents), nil
}

// JobRuns is the resolver for the jobRuns field.
func (r *queryResolver) JobRuns(ctx context.Context) ([]*models.JobRun, error) {
	if _, err := ability.Require(ctx, ability.ActionRead, ability.ResourceJob); err != nil {
		return nil, err
	}
	jobRuns, err := r.Runtime.Store.RecentJobRuns(ctx)
	if err != nil {
		return nil, internalError(err)
	}
	return jobRunPointers(jobRuns), nil
}

// MaintenanceTasks is the resolver for the maintenanceTasks field.
func (r *queryResolver) MaintenanceTasks(ctx context.Context) ([]*models.MaintenanceTask, error) {
	if _, err := ability.Require(ctx, ability.ActionRead, ability.ResourceMaintenance); err != nil {
		return nil, err
	}
	return maintenanceTaskPointers(maintenance.Tasks()), nil
}

// MaintenanceRuns is the resolver for the maintenanceRuns field.
func (r *queryResolver) MaintenanceRuns(ctx context.Context) ([]*models.MaintenanceRun, error) {
	if _, err := ability.Require(ctx, ability.ActionRead, ability.ResourceMaintenance); err != nil {
		return nil, err
	}
	runs, err := r.Runtime.Store.RecentMaintenanceRuns(ctx)
	if err != nil {
		return nil, internalError(err)
	}
	return maintenanceRunPointers(runs), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
