listen_addresses = '*'
max_connections = 20
shared_buffers = 32MB
effective_cache_size = 128MB
work_mem = 1MB
maintenance_work_mem = 16MB
wal_buffers = 1MB
min_wal_size = 32MB
max_wal_size = 128MB
max_worker_processes = 2
max_parallel_workers = 1
max_parallel_workers_per_gather = 0
max_parallel_maintenance_workers = 1
jit = off
fsync = on
synchronous_commit = on

