// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type IncidentInput struct {
	MonitorID *string `json:"monitorId,omitempty"`
	Title     string  `json:"title"`
	Severity  *string `json:"severity,omitempty"`
}

type MonitorInput struct {
	Name            string  `json:"name"`
	URL             string  `json:"url"`
	Method          *string `json:"method,omitempty"`
	ExpectedStatus  *int    `json:"expectedStatus,omitempty"`
	IntervalSeconds *int    `json:"intervalSeconds,omitempty"`
	Enabled         *bool   `json:"enabled,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
